
on:
  push:
    branches: [main]
    paths:
      - 'config/ferris**'
      - 'config/boards/shields/ferris_sweep_v2/**'
  pull_request:
    branches: [main]
  workflow_dispatch:

name: Build Sweep
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.5
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (Ferris Left)
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=ferris_sweep_v2_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Ferris DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/nice_nano_v2.dts.pre.tmp
      - name: Ferris Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 ferris_left_nice_nano_v2.uf2
      - name: Archive (Ferris Left)
        uses: actions/upload-artifact@v2
        with:
          name: firmware_sweep
          path: ferris_left_nice_nano_v2.uf2
      - name: West Build (Ferris Right)
        run: west build --pristine -s zmk/app -b nice_nano_v2 -- -DSHIELD=ferris_sweep_v2_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Ferris Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 ferris_right_nice_nano_v2.uf2
      - name: Archive (Ferris Right)
        uses: actions/upload-artifact@v2
        with:
          name: firmware_sweep
          path: ferris_right_nice_nano_v2.uf2
